project:
  type: book
  output-dir: docs

book:
  title: "Bioestadística Aplicada con R y RStudio"
  author:
    - name: "Arturo Bell Enríquez-García"
      affiliation: "Centro Interdisciplinario de Ciencias Marinas (IPN-CICIMAR)"
  date: "10/25/2022"
  chapters:
    - index.qmd
    - s0_preparacion.qmd
    - part: s01_biolcdatos.qmd
      chapters: 
        - c01_biolcdatos.qmd
        - c02_intro_rs.qmd
        - c03_bases_r.qmd
        - c04_tidyverse.qmd
    - part: s02_fundan.qmd
      chapters:
        - c05_ggplot2.qmd
        - c06_prob.qmd
        - c07_muestreo.qmd
    - part: s03_basics.qmd
      chapters:
        - c08_descriptiva.qmd
        - c09_ph0.qmd
        - c10_param.qmd
        - c11_rls.qmd
    - part: s03_noparnolin.qmd
      chapters:
        - c12_nopar.qmd
        - c13_nolin.qmd
    - part: s04_mv.qmd
      chapters:
        - c14_intromv.qmd
        - c15_nosup.qmd
        - c16_mvcomps.qmd
        - c17_clasif.qmd
        - c18_mvregs.qmd
        - c19_glm.qmd
    - s06_despedida.qmd
    - references.qmd
    
  page-footer: "Arturo Bell"

bibliography: references.bib
csl: peerj.csl
lang: es

format:
  html:
    df-print: paged
    theme: cosmo
#  pdf:
#    documentclass: scrreprt

# execute: 
#   cache: true


