project:
  type: book

book:
  title: "Bioestadística Aplicada con R y RStudio"
  author: "Arturo Bell Enríquez-García"
  date: "10/25/2022"
  chapters:
    - index.qmd
    - s0_preparacion.qmd
    - part: s1_biolcdatos.qmd
      chapters: 
        - c01_biolcdatos.qmd
        - c02_intro_rs.qmd
        - c03_bases_r.qmd
        - c04_ggplot2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    df-print: paged
    theme: cosmo
  pdf:
    documentclass: scrreprt



