---
title: "Misceláneos"
description: |
  Consejos, medio de contacto y alojamiento del sitio
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Consejos

Esta página contiene versiones renderizadas/compiladas de las libretas vistas durante el curso. Si quieres saltar directamente a la ayuda de alguna función, puedes simplemente dar click sobre su nombre dentro de la página.

## Contacto

Si necesitas contactarnos, puedes hacerlo mediante el servidor de Discord o utilizando los medios de contacto señalados en la página de [Dr. Plancton](https://drplancton.com).

## Repositorio

Esta página fue creada utilizando `R`, particularmente con las librerías `RMarkdown` y [`Distill`](https://rstudio.github.io/distill/) (¡sorpresa!) y está alojada en [GitHub](https://github.com). Aunque [git]() no es una herramienta a la que se haga mucha difusión, te recomendamos que te familiarices con ella, pues simplifica mucho el control de cambios y la experimentación. Una forma fácil de ver los beneficios es que te olvidarás de tener archivos con nombre `tesis_final_final_imprimir_corregido.pdf` o similares.
