# Prefacio {.unnumbered}

¡Hola! Te doy la bienvenida al curso Bioestadística Aplicada con `R` y `RStudio`, ofertado por Dr. Plancton.

Este es el libro de acompañamiento del curso. Aquí encontrarás tanto la teoría como el código que se aborda en el curso, dispuestos en una manera que facilita su lectura, y cuyo objetivo es simplemente proveer una versión lista para ser revisada en cualquier momento, sin necesidad de iniciar `RStudio`. Cada sección del libro tiene enlaces a los videos correspondientes, en caso de que prefieras ver y escuchar la explicación.

**Ten en cuenta** que puede existir un desfase entre el material del libro y los videos. La razón es que el material se actualizará para mejorar el contenido, la entrega o la explicación siempre que sea posible, lo cual es fácil de hacer en el libro y las libretas con el código, pero no en los videos; sin embargo, en el momento en el que el desfase sea lo suficientemente grande, también se actualizarán los videos de las secciones correspondientes.

## Objetivos de aprendizaje

El objetivo de este curso es que seas capaz no solo de implementar distintas técnicas de análisis de datos utilizando `R`, sino que también puedas ser crítico con tus resultados y que minimices, en la medida de lo posible, el sesgo algorítmico. En este curso aprenderás los fundamentos detrás de las pruebas vistas, en donde abordaremos la teoría desde un punto de vista práctico, buscando que puedas formarte una intuición propia. También trataremos de desmitificar el valor de p y, sobre todo, cómo no interpretarlo. En las partes más abstractas te adentrarás en el aprendizaje automatizado, y verás que hay vida más allá del $R^2$ (regresiones) y la exactitud (clasificaciones).

Uno de los errores más comunes al enseñar estadística con `R` es tratar de enseñar ambas cosas al mismo tiempo. En este curso, `R` es solo un medio y no un fin; es decir, no es un curso de programación en `R` tanto como es un curso de ciencia de datos aplicada; sin embargo, hay una amplia introducción al lenguaje al inicio, y espero que el explicar línea por línea el código te permita familiarizarte con el lenguaje. Dicho esto, el curso fue diseñado para que personas con nulo o muy poco conocimiento de programación en general puedan seguirlo, y siempre podrás contactarnos en caso de que no hayamos explicado algo adecuadamente.

## `Discord` y acceso al material

Si bien es cierto que puedes utilizar y acceder a todo el material del curso desde esta página, te recomiendo encarecidamente unirte al servidor de `Discord` utilizando tu enlace único (enviado a tu correo al registrarte), pues ahí podrás interactuar no solamente con tus compañeros y compañeras, sino también con tu profesor. Un último comentario, NO es necesario que instales el cliente de `Discord` en tu computadora o dispositivo móvil, aunque si lo haces podrás recibir las notificaciones sobre modificaciones que se hagan al material.

## Estructura del libro

Este libro es, como ya mencioné, el material utilizado en el curso y, por lo tanto, está dividido en distintas secciones, cada una formada por distintos capítulos. Esta división trata de seguir un órden lógico, desde los conceptos y temas más fundamentales hasta los procedimientos más abstractos y, por lo tanto, todos los temas están conectados: cada capítulo asume que ya no tienes ningún problema con los anteriores. 

En cuanto a su uso, en la esquina superior izquierda hay una barra de búsqueda, por si deseas realizar alguna consulta rápida. Debajo tienes todas las secciones y capítulos, en la porción central el contenido y a la derecha la tabla de contenidos del tema que estás leyendo. Referente al contenido, al inicio de cada capítulo tienes el video al tema correspondiete (ojo al desfase), mientras que en el texto encontrarás algunas anotaciones con información relevante al tema:

::: {.callout-note}
Aquí habrá información adicional al tema que se está tratando.
:::

::: {.callout-warning}
Aquí habrá puntos/conceptos/procedimientos con los cuales hay que tener mucho cuidado y la razón.
:::

::: {.callout-important}
Aquí habrá información que es sumamente importante que tengas presente.
:::

También encontrarás resaltados especiales para diferenciar claramente si estoy haciendo referencia a `código en texto`, `funciones`, `librerías` o `software` o a algunos **conceptos clave**. Todo el texto que veas con formato de [hipervínculo](https://youtu.be/V-_O7nl0Ii0?t=17) te llevará a la referencia correspondiente: una figura, un capítulo, un enlace externo o una referencia bibliográfica.

## ¿Compartir o no compartir? He ahí el dilema

No hay nada que te impida compartir este libro y con ello todo el curso. De hecho, nada me daría más gusto que saber que el curso te fue lo suficientemente agradable y útil como para dirigirlo a alguien más, pero te pido que lo hagas lo menos posible. Tu acceso al curso es vitalicio, pero ni el contenido ni el material son estáticos, por lo que dependemos de las nuevas ventas para poder seguir mejorándolo y mantenerlo en línea. Si quieres compartirlo puedes utilizar tu código de referido, el cuál da un descuento adicional a cualquier otro descuento o promoción.

Dicho esto, te doy nuevamente la bienvenida y espero que el curso cubra con tus expectativas (y un poco más).