# Despedida

Con esto llegamos al final del curso. ¡Muchas felicidades! Acabas de pasar por un camino bastante escabroso, con algunas cosas bastante digeribles, y otras que son un dolor de cabeza, pero espero que el contenido haya sido de tu agrado, que te hayas llevado algo y, sobre todo, que lo aprendido te sea útil. En este momento cuentas con bases sólidas tanto para adentrarte más en cualquiera de los temas aquí vistos como para incursionar en otros temas. Una recomendación personal es revisar un paradigma de inferencia diferente: la Inferencia Bayesiana. Puedes también adentrarte más en el área del aprendizaje automatizado, pues es un mundo con un potencial enorme de aplicación a problemas biológicos.

Por último, recuerda que no porque podamos hacer algo quiere decir que debamos de hacerlo. Nada me daría más gusto que saber que el curso te motivó a aplicar en tus análisis alguna de las técnicas que aquí vimos, pero siempre pregúntate si es pertinente para responder la pregunta que quieres responder.

Sin más que agregar, te deseo lo mejor, hoy y siempre.