---
title: "Estadística No Paramétrica"
author: "Arturo Bell Enríquez García"
output: html_notebook
---

Hasta ahora habíamos tratado con pruebas y técnicas que requieren ciertas características, particularmente normalidad y homocedasticidad, para dar resultados confiables. Pero, ¿qué pasa cuando nuestros datos no se ajustan a una distribución normal o tenemos muestras heterocedásticas? Una opción es recurrir a algún método de transformación de datos, pero eso lo abordaremos en otra ocasión. En este momento hablaremos sobre una familia de técnicas cuyos requerimientos sobre las distribuciones de los datos no son tan estrictos, aunquetambién suelen ser menos sensibles que los análisis paramétricos: Las pruebas NO paramétricas.



```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

