---
title: "Evaluación final (Opción 1)"
author: "AGREGA TU NOMBRE"
output: 
  html_notebook:
    toc: yes
---

## Descripción
Este ejercicio de evaluación consistirá en utilizar un conjunto de datos para resolver tres (3) preguntas sobre una base de datos, ya sea propia o la aquí provista.
La estructura para cada una deberá ser:

1. Planteamiento del problema/Hipótesis de trabajo
2. Técnica a utilizar y justificación
3. Juego de hipótesis estadísticas (de haberlas o justificar por qué no hay)
4. Supuestos y comprobación (de haberlos)
5. Implementación de la técnica (incluir cualquier procesamiento previo a los datos y su justificación)
5. Reporte de resultados, incluir al menos una gráfica que siga las recomendaciones del tema de Representaciones de la Realidad.

En caso de utilizar los datos proporcionados toma en cuenta la siguiente descripción de los [datos](https://doi.org/10.5061/dryad.1ns7n):

`annual_perennial_abundance.csv`:
Este conjunto de datos contiene abundancias anuales para todos los sitios y años (2008-2012), así como alturas de perennes en cm (2009-2012) y porcentajes de cobertura de tierra (2008-2012).

`environmental_data.csv`: Datos ambientales a lo largo del gradiente latitudinal.
Este archivo contiene datos sobre las condiciones bióticas y abióticas experimentadas por gremios anuales y perennes a lo largo del gradiente latitudinal muestreado. Las variables incluyen la lluvia promedio (mm), temperaturas (ºC, promedio mensual máximo, mínimo y promedio diario), horas de luz solar promedio en otoño, primavera e invierno, número promedio de pellets fecales (intensidad de pastoreo), concentración promedio de nitrógeno en suelo, cubierta promedio y ancho del "tapete" de briofitas y correlación promedio entre abundancias anuales y la cobertura de briofitas.

## Pregunta 1

## Pregunta 2

## Pregunta 3