---
title: "Bioestadistica con R y RStudio"
description: |
  ¡Bienvenidos y Bienvenidas al sitio del curso!
author:
  - name: "M en C. Arturo Bell Enríquez García"
    affiliation: "Centro Interdisciplinario de Ciencias Marinas"
  - name: "Biol. Mar. Roberto Iván Velásquez Polanco"
    affiliation: "Dr. Plancton"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      R.options = list(width = 80))

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

Esta es la página con el material del curso Bioestadística Aplicada con R y RStudio, ofrecido por Dr. Plancton. Aquí encontrarás el código revisado en el curso, presentado en una manera que facilita su lectura y cuyo objetivo es simplemente proveer una versión más amable visualmente que la interfaz de RStudio. Todo el código que verás aquí son las versiones compiladas de las libretas vistas en las sesiones. La única diferencia es que vas a encontrar un `"data/..."` dentro de las funciones para cargar los datos. Esto no tiene nada de extraño, simplemente fue para ayudarnos en la construcción de este sitio.

## Objetivo de aprendizaje

El objetivo de este curso es que seas capaz no solo de implementar distintas técnicas de análisis de datos utilizando R, sino que también puedas ser crítico con tus resultados y que minimices, en la medida de lo posible, el sesgo algorítmico. Nuestro objetivo principal es que, después de este curso, puedas evaluar de manera objetiva tus análisis y resultados y describirlos adecuadamente.

## Discord

Si bien es cierto que puedes utilizar y acceder a todo el material del curso desde esta página, te recomendamos encarecidamente unirte al servidor de discord utilizando tu enlace **único** (enviado a tu correo al registrarte), pues ahí podrás interactuar no solamente con otros compañeros, sino también con los profesores. Un último comentario, NO es necesario que instales el cliente de Discord en tu computadora o dispositivo móvil.

## R y RStudio

Para poder aplicar el código que se presenta vas a necesitar instalar [R](https://www.r-project.org/) y [RStudio](https://www.rstudio.com/). El proceso de instalación es, regularmente, sencillo. Simplemente descarga el instalador de la versión más reciente de R para tu sistema operativo, sigue los pasos en el instalador y luego instala RStudio (la versión gratuita).


